name: Build Multi-Arch Images

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPOSITORY: xjonathanlei/nginx-socks
      NGINX_VERSION: 1.18.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Enable Docker Buildx
        run: |
          jq '. + {"experimental":"enabled"}' ~/.docker/config.json > ~/.docker/config_new.json && mv ~/.docker/config_new.json ~/.docker/config.json
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          sudo systemctl restart docker
          docker buildx create --name multi_builder
          docker buildx use multi_builder

      - name: Build linux/amd64 Image
        run: |
          docker buildx build -t ${DOCKER_REPOSITORY}:${NGINX_VERSION}-amd64 --platform linux/amd64 --build-arg NGINX_VERSION="${NGINX_VERSION}" --output=type=docker .

      - name: Build linux/arm64 Image
        run: |
          docker buildx build -t ${DOCKER_REPOSITORY}:${NGINX_VERSION}-arm64 --platform linux/arm64 --build-arg NGINX_VERSION="${NGINX_VERSION}" --output=type=docker .

      - name: Push Multi-Arch Images
        run: |
          docker push ${DOCKER_REPOSITORY}:${NGINX_VERSION}-amd64
          docker push ${DOCKER_REPOSITORY}:${NGINX_VERSION}-arm64
          docker manifest create ${DOCKER_REPOSITORY}:${NGINX_VERSION} \
            ${DOCKER_REPOSITORY}:${NGINX_VERSION}-amd64 \
            ${DOCKER_REPOSITORY}:${NGINX_VERSION}-arm64
          docker manifest create ${DOCKER_REPOSITORY}:latest \
            ${DOCKER_REPOSITORY}:${NGINX_VERSION}-amd64 \
            ${DOCKER_REPOSITORY}:${NGINX_VERSION}-arm64
          docker manifest push ${DOCKER_REPOSITORY}:${NGINX_VERSION}
          docker manifest push ${DOCKER_REPOSITORY}:latest
